language: python
python:
  - "3.8.1"
before-install: 
- "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
- pip install -r requirements.txt
script:
- pytest
[![Travis][build-badge]][build]

[build-badge]:https://img.shields.io/travis/PeganovOleg/e1_12/master.png?style=flat-square

[build]:https://travis-ci.org/PeganovOleg/e1_12
